### ISSUE TITLE
Does it support Cassandra 3.11? 

### ISSUE THREAD

**Issue by ritu0407** [spotify/cassandra-reaper#153]
Getting issue while using it with Cassandra 3.11:

WARN [2017-07-27 04:16:44,669] [testcluster:1:355] c.s.r.s.SegmentRunner - SegmentRunner declined to repair segment 355 because of an error collecting information from one of the hosts (127.0.0.1): {}
java.lang.reflect.UndeclaredThrowableException: null
at com.sun.proxy.$Proxy51.getPendingTasks(Unknown Source) ˜[na:1.8.0-internal]
at com.spotify.reaper.cassandra.JmxProxy.getPendingCompactions(JmxProxy.java:259) ˜[cassandra-reaper-1.1.1-SNAPSHOT.jar:1.1.1-SNAPSHOT]
at com.spotify.reaper.service.SegmentRunner.canRepair(SegmentRunner.java:262) [cassandra-reaper-1.1.1-SNAPSHOT.jar:1.1.1-SNAPSHOT]
at com.spotify.reaper.service.SegmentRunner.runRepair(SegmentRunner.java:178) [cassandra-reaper-1.1.1-SNAPSHOT.jar:1.1.1-SNAPSHOT]
at com.spotify.reaper.service.SegmentRunner.run(SegmentRunner.java:96) [cassandra-reaper-1.1.1-SNAPSHOT.jar:1.1.1-SNAPSHOT]
Caused by: javax.management.AttributeNotFoundException: No such attribute: PendingTasks
at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:93) ˜[na:1.8.0-internal]
at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:218) ˜[na:1.8.0-internal]
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:659) ˜[na:1.8.0-internal]
at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:690) ˜[na:1.8.0-internal]

**Comment by deniszh** [comment]
Try TLP fork (https://github.com/thelastpickle/cassandra-reaper) - maybe it works.

**Comment by mrwulf** [comment]
I can confirm the TLP fork works with 3.11.0.
