### ISSUE TITLE
SchedulingManager throwing exceptions and not starting any new repairs

### ISSUE THREAD

**Issue by Bj0rnen** [spotify/cassandra-reaper#99]
I discovered that our production reaper has not started repairs that were on schedule for nearly 5 days. Many schedules now have a next_activation date in the past. The log shows this exception being thrown repeatedly:

com.spotify.reaper.ReaperException: failed to generate repair segments for cluster "insert_cluster_name_here"
        at com.spotify.reaper.resources.CommonTools.generateSegments(CommonTools.java:113) ~[cassandra-reaper-0.2.1-SNAPSHOT.jar:0.2.1-SNAPSHOT]
        at com.spotify.reaper.resources.CommonTools.registerRepairRun(CommonTools.java:60) ~[cassandra-reaper-0.2.1-SNAPSHOT.jar:0.2.1-SNAPSHOT]
        at com.spotify.reaper.service.SchedulingManager.startNewRunForUnit(SchedulingManager.java:160) ~[cassandra-reaper-0.2.1-SNAPSHOT.jar:0.2.1-SNAPSHOT]
        at com.spotify.reaper.service.SchedulingManager.manageSchedule(SchedulingManager.java:133) ~[cassandra-reaper-0.2.1-SNAPSHOT.jar:0.2.1-SNAPSHOT]
        at com.spotify.reaper.service.SchedulingManager.run(SchedulingManager.java:82) ~[cassandra-reaper-0.2.1-SNAPSHOT.jar:0.2.1-SNAPSHOT]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_60]
        at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_60]

**Comment by Bj0rnen** [comment]
Should be solved by #100.
